### ISSUE TITLE
upload image

### ISSUE THREAD

**Issue by aepsh** [oreHGA/faceRekognizer#1]
i'm cant upload the image. in server say:
Listening on localhost:3128
sending to Kairos for training
Image Attributes : 
[object Object]

**Comment by oreHGA** [comment]
hi, when you get this, this means that your image has been successfully uploaded to Kairos, you can now go ahead to trying to verify

**Comment by oreHGA** [comment]
this commit https://github.com/oreHGA/faceRekognizer/commit/51e1b8fdf8467ff33c6b3d04b0566d3bdfe07108
 fixes the error that made you not get the response on the frontend server after your image is successfully uploaded. Sorry about that
